trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: clusterName
    displayName: Cluster name
    type: string
  - name: baseDomain
    displayName: Base domain
    type: string
  - name: networkResourceGroup
    displayName: Network resource group
    type: string
  - name: networkName
    displayName: Network name
    type: string 
  - name: sshKey
    displayName: SSH key
    type: string
  - name: ocpVersion
    displayName: OpenShift version (x.y)
    default: "4.6"

steps:
- task: Bash@3
  displayName: Acquire OpenShift installer
  inputs:
    targetType: 'inline'
    script: 'curl --location --fail --silent --show-error https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-${{ parameters.ocpVersion }}/openshift-install-linux.tar.gz -o openshift-install.tar.gz' 
    failOnStderr: true 

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'openshift-install.tar.gz' 
    destinationFolder: .
    cleanDestinationFolder: false 

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ocp-4-sa-azdo'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'
    addSpnToEnvironment: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
