trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: azureRegion
    displayName: Azure region
    type: string
    default: "northeurope"

  - name: networkResourceGroup
    displayName: Network resource group
    type: string
    default: "networking-rg"

  - name: openShiftResourceGroup
    displayName: OpenShift resource group
    type: string
    default: "openshift-1-rg"

  - name: ocpVersion
    displayName: OpenShift version (x.y)
    default: "4.6"

  - name: clusterName
    displayName: Cluster name
    type: string
    default: "devtest"

  - name: baseDomain
    displayName: Base domain
    type: string
    default: "ocp.aerdei.private"

  - name: networkName
    displayName: Network name
    type: string
    default: "ocp-4-vnet"

  - name: controlPlaneSubnet
    displayName: Control plane subnet
    default: "ocp-4-master-subnet"

  - name: computeSubnet
    displayName: Compute node subnet
    default: "ocp-4-worker-subnet"

variables:
  - group: ocp-4-variable-group

steps:
  - task: Bash@3
    displayName: Acquire OpenShift installer
    inputs:
      targetType: "inline"
      script: "curl --location --fail --silent --show-error https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-${{ parameters.ocpVersion }}/openshift-install-linux.tar.gz -o openshift-install.tar.gz"
      failOnStderr: true

  - task: ExtractFiles@1
    displayName: Extract OpenShift installer
    inputs:
      archiveFilePatterns: "openshift-install.tar.gz"
      destinationFolder: .
      cleanDestinationFolder: false

  - task: Bash@3
    displayName: Prepare OpenShift install config file
    inputs:
      targetType: "inline"
      script: |
        mkdir ${{ parameters.clusterName }}
        envsubst < ./installer/install-config.bk.yaml > ./${{ parameters.clusterName }}/install-config.yaml
        cat ./${{ parameters.clusterName }}/install-config.yaml
      failOnStderr: true
    env:
      BASE_DOMAIN: "${{ parameters.baseDomain }}"
      CLUSTER_NAME: "${{ parameters.clusterName }}"
      AZURE_REGION: "${{ parameters.azureRegion }}"
      OCP_RG: "${{ parameters.openShiftResourceGroup }}"
      VNET_RG: "${{ parameters.networkResourceGroup }}"
      VNET_NAME: "${{ parameters.networkName }}"
      CONTROL_PLANE_SUBNET: "${{ parameters.controlPlaneSubnet }}"
      COMPUTE_SUBNET: "${{ parameters.computeSubnet }}"
      PULL_SECRET: $(ocp-4-pullsecret)
      SSH_KEY: $(ocp-4-ssh-pub)

  - task: AzureCLI@2
    displayName: Get subscriptionId
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        subscriptionId=`az account show | jq -r -c .id`
        echo "##vso[task.setvariable variable=subscriptionId;]$subscriptionId"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: Bash@3
    displayName: Prepare osServicePrincipal.json
    inputs:
      targetType: "inline"
      script: |
        jq --arg key0 'subscriptionId' \
        --arg value0 '$(subscriptionId)' \
        --arg key1 'clientId'   \
        --arg value1 '$(ocp-4-sp-id)' \
        --arg key2 'clientSecret'  \
        --arg value2 '$(ocp-4-sp-pw)' \
        --arg key3 'tenantId' \
        --arg value3 '$(ocp-4-sp-tid)' \
        '. | .[$key0]=$value0 | .[$key1]=$value1 | .[$key2]=$value2 | .[$key3]=$value3' <<< {} | tee osServicePrincipal.json
      failOnStderr: true

  - task: Bash@3
    displayName: Prepare OpenShift manifest files
    inputs:
      targetType: "inline"
      script: |
        ./openshift-install create manifests --dir=./${{ parameters.clusterName }} --log-level error
        rm -f ./${{ parameters.clusterName }}/openshift/99_openshift-cluster-api_master-machines-*.yaml
        rm -f ./${{ parameters.clusterName }}/openshift/99_openshift-cluster-api_worker-machineset-*.yaml
        sed -i 's/mastersSchedulable: true/mastersSchedulable: false/g' ./${{ parameters.clusterName }}/manifests/cluster-scheduler-02-config.yml
      failOnStderr: true
    env:
      AZURE_AUTH_LOCATION: ./osServicePrincipal.json

  - task: Bash@3
    displayName: Get infraId variable
    inputs:
      targetType: "inline"
      script: |
        infraId=`grep -oP "(?<=infrastructureName: ).*" ./${{ parameters.clusterName }}/manifests/cluster-infrastructure-02-config.yml`
        echo "##vso[task.setvariable variable=infraId;]$infraId"
      failOnStderr: true

  - task: Bash@3
    displayName: Create ignition configs
    inputs:
      targetType: "inline"
      script: "./openshift-install create ignition-configs  --dir=./${{ parameters.clusterName }} --log-level error"
      failOnStderr: true

  - task: AzureCLI@2
    displayName: Deploy identity
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment group create --template-file "./templates/01_identity.json" --parameters baseName='$(infraId)' --parameters networkResourceGroup="${{ parameters.networkResourceGroup }}" -g "${{ parameters.openShiftResourceGroup }}"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Deploy storage
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/02_storage.json" --parameters baseName='$(infraId)'
        storageAccountName=`az deployment group show -g "${{ parameters.openShiftResourceGroup }}" -n 02_storage --query properties.outputs.storageAccountName.value -o tsv`
        storageAccountKey=`az deployment group show -g "${{ parameters.openShiftResourceGroup }}" -n 02_storage --query properties.outputs.storageAccountKey.value -o tsv`
        echo "##vso[task.setvariable variable=storageAccountName;]$storageAccountName"
        echo "##vso[task.setvariable variable=storageAccountKey;]$storageAccountKey"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Copy VHD to blob container
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        vhdUrl=$(curl -s https://raw.githubusercontent.com/openshift/installer/release-4.6/data/data/rhcos.json | jq -c -r .azure.url)
        az storage blob copy start --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --destination-blob "rhcos.vhd" --destination-container vhd --source-uri $vhdUrl
        echo "`date -Iseconds`: started blob copy."
        status="unknown"
        while [ "$status" != "success" ]
        do
          status=`az storage blob show --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --container-name vhd --name "rhcos.vhd" -o tsv --query properties.copy.status`
          echo "`date -Iseconds`: progress is $status."
          sleep 60s
        done
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Upload bootstrap ignition config
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az storage blob upload --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' -c "files" -f "./${{ parameters.clusterName }}/bootstrap.ign" -n "bootstrap.ign"
      addSpnToEnvironment: true

  - task: AzureCLI@2
    displayName: Deploy infrastructure components
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        vhdBlobUrl=`az storage blob url --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' -c vhd -n "rhcos.vhd" -o tsv`
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/03_infra.json" --parameters privateDNSZoneName="${{ parameters.clusterName }}.${{ parameters.baseDomain }}" --parameters baseName='$(infraId)' --parameters networkResourceGroupName="${{ parameters.networkResourceGroup }}" --parameters virtualNetworkName="${{ parameters.networkName }}" --parameters vhdBlobURL="$vhdBlobUrl"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Deploy bootstrap components
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        bootstrapUrl=`az storage blob url --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' -c "files" -n "bootstrap.ign" -o tsv`
        bootstrapIgnition=`jq -rcnM --arg v "3.1.0" --arg url "$bootstrapUrl" '{ignition:{version:$v,config:{replace:{source:$url}}}}' | base64 -w0`
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/04_bootstrap.json" --parameters bootstrapIgnition="$bootstrapIgnition" --parameters sshKeyData="$(ocp-4-ssh-pub)" --parameters baseName='$(infraId)' --parameters networkResourceGroupName="${{ parameters.networkResourceGroup }}" --parameters virtualNetworkName="${{ parameters.networkName }}"
      addSpnToEnvironment: true
      failOnStandardError: true
  - task: AzureCLI@2
    displayName: Deploy control plane components
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        controlPlaneIgnition=$(base64 -w0 < $cluster_install_dir/master.ign)
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/05_control_plane.json" --parameters masterIgnition="$controlPlaneIgnition" --parameters sshKeyData='$(ocp-4-ssh-pub)' --parameters privateDNSZoneName="${{ parameters.clusterName }}.${{ parameters.baseDomain }}" --parameters baseName='$(infraId)' --parameters networkResourceGroupName="${{ parameters.networkResourceGroup }}" --parameters virtualNetworkName="${{ parameters.networkName }}"
      addSpnToEnvironment: true
      failOnStandardError: true

