apiVersion: v1
baseDomain: ocp.aerdei.private
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: devtest
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/14
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: northeurope
  # baseDomainResourceGroupName: ocp4-cluster-child
    resourceGroupName: openshift-1-rg
    outboundType: UserDefinedRouting
    networkResourceGroupName: networking-rg
    virtualNetwork: ocp-4-vnet
    controlPlaneSubnet: ocp-4-master-subnet 
    computeSubnet: ocp-4-worker-subnet
publish: Internal
credentialsMode: Passthrough
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FlcmRlaTFyZWRoYXRjb20xaXI5bnlwY3dwbGphYXYyb25waXV3NXFvOGs6VlVYWTJMODBCSTdaU0xUSjdRN0hSWk1HWUgwMVc3TjE0UllZVlZMUkZIMzlHM1oxWENNR1JHVEFVSVNQWVhQVA==","email":"aerdei@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FlcmRlaTFyZWRoYXRjb20xaXI5bnlwY3dwbGphYXYyb25waXV3NXFvOGs6VlVYWTJMODBCSTdaU0xUSjdRN0hSWk1HWUgwMVc3TjE0UllZVlZMUkZIMzlHM1oxWENNR1JHVEFVSVNQWVhQVA==","email":"aerdei@redhat.com"},"registry.connect.redhat.com":{"auth":"NTE1ODM0MTl8dWhjLTFJUjlueVBjV3BMSkFhdjJPbnBpdXc1cW84azpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdObUppWVRabU1HRmpPV0kwTnpZNFlUWmtZMkpqWVRWaVpEQmxOREpqTWlKOS5GaXd3OFJDY3dydFN1NmVZUURaWnl0X2dJX1NQYjQzcXpWczRQVGJveG5qeVhjeDlfZWNDR2xpS2I5NjR5QklIVnVfX1lnTHhVQm9rQ05BeldNUTFrbEw0UkhXbjNSajZSQzF3a0l2TmVaNHR1ekhZeGVXZXJaUnQ3Qk9ZLTVKQ19ZX3dWVFIzQ0kxYTJQMmdmTDEzdWlFMktFX0duV3hWZ2xodFREUjNpVFU4U1FmM1E2Q25ka05WN0NhOEREQ0phVGVUZm9CU1hQU0VMX0hhempJTThUcm9lNExfNmE0WHp4bWwxUHVtc3FLalVvQVQ0RUxmaUpEdGppaDctWDM1cm1ZbTNadHVvUjFCY01BSHNaRkhJV3M0SFVfLTkyd25pai14eks5enRmSVd2eXFWWmxqT1NoMFdlUGxzaTBSNFFZaEtuQ09pSEhiTU9ySHN5dUNXMGJ5NDVzSjNLQ1U0MTBNcFdaUjVYZzQzNzBmWmxGMkNwb1JCYVJlQXdna2RWcjRVNElxLVpJUlpUS003MEpUQ3N4SFg3MUZrdlBqV0k1SVQ5cG84MS1YOTVkT29xcl8xdXlVSHc5SE1aOTdDNnliaGVxUXVfQUpzRVBPd3pVYWtNWDZBTXBLR2hpcWtObHcyOF90d0lWcWw5cUJ3cklTLVIwLTJrWUJxckhCbUZjcGZBYk9laE13bU1yZU1Pd05xanhMazlISHdCekgtaURUS2Z0anBZZ2d6VEJoV3d1SF9GWTZTNUEtRl9Ubjdab2NtUWlVOGxiOWNDTlI0N0dqVU1pZ3hJM2xCeWFYck8xSlk3SG90SGJHNWZ3aVVOVXpUb0tSTHl0NEZrVVZkenB3V3FZa0tEeHlNNUJlZ19LVmxXamNvVV9PNS1nTjd2Snl6OVpvTU94VQ==","email":"aerdei@redhat.com"},"registry.redhat.io":{"auth":"NTE1ODM0MTl8dWhjLTFJUjlueVBjV3BMSkFhdjJPbnBpdXc1cW84azpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdObUppWVRabU1HRmpPV0kwTnpZNFlUWmtZMkpqWVRWaVpEQmxOREpqTWlKOS5GaXd3OFJDY3dydFN1NmVZUURaWnl0X2dJX1NQYjQzcXpWczRQVGJveG5qeVhjeDlfZWNDR2xpS2I5NjR5QklIVnVfX1lnTHhVQm9rQ05BeldNUTFrbEw0UkhXbjNSajZSQzF3a0l2TmVaNHR1ekhZeGVXZXJaUnQ3Qk9ZLTVKQ19ZX3dWVFIzQ0kxYTJQMmdmTDEzdWlFMktFX0duV3hWZ2xodFREUjNpVFU4U1FmM1E2Q25ka05WN0NhOEREQ0phVGVUZm9CU1hQU0VMX0hhempJTThUcm9lNExfNmE0WHp4bWwxUHVtc3FLalVvQVQ0RUxmaUpEdGppaDctWDM1cm1ZbTNadHVvUjFCY01BSHNaRkhJV3M0SFVfLTkyd25pai14eks5enRmSVd2eXFWWmxqT1NoMFdlUGxzaTBSNFFZaEtuQ09pSEhiTU9ySHN5dUNXMGJ5NDVzSjNLQ1U0MTBNcFdaUjVYZzQzNzBmWmxGMkNwb1JCYVJlQXdna2RWcjRVNElxLVpJUlpUS003MEpUQ3N4SFg3MUZrdlBqV0k1SVQ5cG84MS1YOTVkT29xcl8xdXlVSHc5SE1aOTdDNnliaGVxUXVfQUpzRVBPd3pVYWtNWDZBTXBLR2hpcWtObHcyOF90d0lWcWw5cUJ3cklTLVIwLTJrWUJxckhCbUZjcGZBYk9laE13bU1yZU1Pd05xanhMazlISHdCekgtaURUS2Z0anBZZ2d6VEJoV3d1SF9GWTZTNUEtRl9Ubjdab2NtUWlVOGxiOWNDTlI0N0dqVU1pZ3hJM2xCeWFYck8xSlk3SG90SGJHNWZ3aVVOVXpUb0tSTHl0NEZrVVZkenB3V3FZa0tEeHlNNUJlZ19LVmxXamNvVV9PNS1nTjd2Snl6OVpvTU94VQ==","email":"aerdei@redhat.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCaxfJ1yePdRM64HAZVPCr7+Wt2685N2kDhxopqOz/W/kPv66lmzjp0zk+H/mQQjnXoq6uI3k/lXX5wn2ctpQProQW6RNbRSQ2CsOMvYsl+AH5IoZPNAY5tyB/Lwkn6O56+3aZctc2UdHF52aVufmnI47NPgVVm39WAHNW/VV4JNWxvT7rM1+ajDOVYNVJfZvS84Nom9VeUhbV+u0jhp1BDhUNwqQuaYd6WercjRqkbhkZfKF+aDCeHIvE1sAlsuj4JhfuInkeQYBzZU2VVoMJnXivc61BkFAA0Q2TKipGwLhjFDuXK2L+j8DOkAkTV7tX6jtwbIkBlYn9St2LAbBhOvGECjH8N+yks00Dn3QoplVGAUvUO1DEIpLRUbQRHFYO+8uwkygouCNtHKvSsN2yaLMQ/YqECOiMWPby4HZEGgumseHRE7K6vTzJVfbKNNA+/hPB0lisYHWSTk3EHsnYGGu1D7oddQ8X3qQYy5whoiIgixCM02UefCPynZUvO0p0= aerdei@DESKTOP-3HHGD3V' 
